openapi: 3.0.0
info:
  title: Coronatime API
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: local server

paths:
  /countries:
    get:
      summary: Get countries
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
