name: Deploy to Production

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd apps
            cd coronatime-api
            npm ci
            pm2 restart coronatime-api
